# tasks file for php-fpm
# TODO: Fix versions

- name: Show stub
  debug:
    msg: Installing nginx

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure php-fpm packages are installed
  apt:
    name: "{{ item }}"
  loop:
    - php-fpm
    - php-pgsql
