# handlers file for php-fpm
- name: restart php-fpm
  service:
    name: "php{{ php_fpm_version }}-fpm"
    state: restarted

- name: reload php-fpm
  service:
    name: "php{{ php_fpm_version }}-fpm"
    state: reloaded
