---
# tasks file for app_deploy

- name: Check permissions
  file:
    path: "{{ www_site_root }}"
    owner: "{{ app_wwwuser }}"
    group: "{{ app_wwwuser }}"

- name: Deploy index.php
  copy:
    src: index.php
    dest: "{{ www_site_root }}/index.php"
    owner: "{{ app_wwwuser }}"
    group: "{{ app_wwwuser }}"
