---
# tasks file for app_deploy

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Ensure packages are installed
  apt:
    name: "{{ item }}"
  loop:
    - rsync

- name: Deploy site
  synchronize:
    owner: no
    group: no
    src: 'files/'
    dest: "{{ www_site_root }}/"

- name: Check permissions
  file:
    path: "{{ www_site_root }}"
    owner: "{{ app_wwwuser }}"
    group: "{{ app_wwwuser }}"
    recurse: yes
