---
# tasks file for nginx
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Ensure nginx packages are installed
  apt:
    name: "{{ item }}"
  loop:
    - nginx
  notify: restart nginx

- name: Delete default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy template
  template:
    src: site.j2
    dest: /etc/nginx/sites-available/site
  notify: reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/site
    dest: /etc/nginx/sites-enabled/site
    state: link

- name: Create nginx_root
  file:
    path: "{{ nginx_site_root }}"
    state: directory

- name: Touch access_list.conf
  file:
    path: /etc/nginx/access_list.conf
    state: touch
    owner: "{{ nginx_wwwuser }}"
    group: "{{ nginx_wwwuser }}"
    access_time: preserve
    modification_time: preserve

- name: Start the nginx service
  service:
    name: nginx
    state: started
    enabled: true
