---
- name: Install pgsql on master
  hosts: dbmaster
  become: true

  roles:
    - role: pgsql_ms
      pgsql_type: master
      tags: db, dbmaster

- name: Install pgsql on slave
  hosts: dbslave
  become: true

  roles:
    - role: pgsql_ms
      pgsql_type: slave
      tags: db, dbslave
